kk_job:
    path:  /
    defaults: { _controller: "KKJobeetBundle:Job:index" }

kk_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "KKJobeetBundle:Job:show" }
    requirements:
        id:  \d+

kk_job_preview:
    path: /{company}/{location}/{token}/{position}
    defaults: { _controller: "KKJobeetBundle:Job:preview" }
    requirements:
        token: \w+

kk_job_new:
    path:  /new
    defaults: { _controller: "KKJobeetBundle:Job:new" }

kk_job_create:
    path:  /create
    defaults: { _controller: "KKJobeetBundle:Job:create" }
    requirements: { _method: post }

kk_job_edit:
    path:  /{token}/edit
    defaults: { _controller: "KKJobeetBundle:Job:edit" }

kk_job_update:
    path:  /{token}/update
    defaults: { _controller: "KKJobeetBundle:Job:update" }
    requirements: { _method: post|put }

kk_job_delete:
    path:  /{token}/delete
    defaults: { _controller: "KKJobeetBundle:Job:delete" }
    requirements: { _method: post|delete }

kk_job_publish:
    path:  /{token}/publish
    defaults: { _controller: "KKJobeetBundle:Job:publish" }
    requirements: { _method: post }
