admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

kk_jobeet:
    resource: "@KKJobeetBundle/Resources/config/routing.yml"
    prefix:   /


